export const FONTS = [
  { label: '기본 글꼴', value: '' },
  { label: 'Source Han Sans (思源黑体)', value: 'SourceHanSans' },
  { label: 'Source Han Serif (思源宋体)', value: 'SourceHanSerif' },
  { label: 'FZ Heiti (方正黑体)', value: 'FangZhengHeiTi' },
  { label: 'FZ Kaiti (方正楷体)', value: 'FangZhengKaiTi' },
  { label: 'FZ Songti (方正宋体)', value: 'FangZhengShuSong' },
  { label: 'FZ Fangsong (方正仿宋)', value: 'FangZhengFangSong' },
  { label: 'Alibaba PuHuiTi (阿里巴巴普惠体)', value: 'AlibabaPuHuiTi' },
  { label: 'Zhuque Fangsong (朱雀仿宋)', value: 'ZhuqueFangSong' },
  { label: 'LXGW WenKai (霞鹜文楷)', value: 'LXGWWenKai' },
  { label: 'WenDing PL Kaiti (文鼎PL楷体)', value: 'WenDingPLKaiTi' },
  { label: 'DeYiHei (得意黑)', value: 'DeYiHei' },
  { label: 'MiSans', value: 'MiSans' },
  { label: 'Canger Xiaowanzi (仓耳小丸子)', value: 'CangerXiaowanzi' },
  { label: 'Youshe Title Black (优设标题黑)', value: 'YousheTitleBlack' },
  { label: 'Fengguang Mingrui (峰广明锐体)', value: 'FengguangMingrui' },
  { label: 'Shetu Modern Square (摄图摩登小方体)', value: 'ShetuModernSquare' },
  { label: 'Zcool Happy (站酷快乐体)', value: 'ZcoolHappy' },
  { label: 'ZizhiQu XiMai (字制区喜脉体)', value: 'ZizhiQuXiMai' },
  { label: 'SucaiJishi Kangkang (素材集市康康体)', value: 'SucaiJishiKangkang' },
  { label: 'SucaiJishi CoolSquare (素材集市酷方体)', value: 'SucaiJishiCoolSquare' },
  { label: 'Tuniu Rounded (途牛类圆体)', value: 'TuniuRounded' },
  { label: 'Ruizi Zhenyan (锐字真言体)', value: 'RuiziZhenyan' },
]
