export const FONTS = [
  { label: '기본 글꼴', value: '' },
  // 한글 폰트
  { label: '노토 산스', value: 'Noto Sans KR' },
  { label: '나눔 고딕', value: 'Nanum Gothic' },
  { label: '나눔 명조', value: 'Nanum Myeongjo' },
  { label: '노토 세리프', value: 'Noto Serif KR' },
  { label: '주아', value: 'Jua' },
  { label: '도현', value: 'Do Hyeon' },
  { label: '검은고딕', value: 'Black Han Sans' },
  { label: '가소원', value: 'Gasoek One' },
  { label: '함렛', value: 'Hahmlet' },
  { label: '고운 바탕', value: 'Gowun Batang' },
  // 한글 웹폰트 (추가)
  { label: 'Pretendard', value: 'Pretendard' },
  { label: 'Paperlogy', value: 'Paperlogy' },
  { label: 'Freesentation', value: 'Freesentation' },
  { label: '쿠키런', value: 'CookieRun' },
  { label: '넥슨 Lv2 고딕', value: 'NEXON Lv2 Gothic' },
  { label: '메이플스토리', value: 'MaplestoryOTF' },
  // 영어 폰트
  { label: 'Roboto', value: 'Roboto' },
  { label: 'Open Sans', value: 'Open Sans' },
  { label: 'Playfair Display', value: 'Playfair Display' },
  { label: 'Lora', value: 'Lora' },
  { label: 'Ubuntu', value: 'Ubuntu' },
  { label: 'DM Sans', value: 'DM Sans' },
  { label: 'Fira Sans', value: 'Fira Sans' },
  { label: 'PT Serif', value: 'PT Serif' },
  { label: 'Bebas Neue', value: 'Bebas Neue' },
  { label: 'Anton', value: 'Anton' },
  // 시스템 폰트 추가
  { label: 'Calibri', value: 'Calibri' },
  { label: 'Arial', value: 'Arial' },
  { label: 'Verdana', value: 'Verdana' },
  { label: 'Helvetica', value: 'Helvetica' },
  { label: 'Times New Roman', value: 'Times New Roman' },
]
